# Assumes all service accounts have root access
#   Configure via: `kubectl create clusterrolebinding serviceaccounts-cluster-admin   --clusterrole=cluster-admin   --group=system:serviceaccounts`
#
# After applying run `kubectl get secret/github-actions-service-account -n flickr-api-proxy -o yaml` and copy the result into
#   the GitHub secret K8S_SECRET
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: flickr-api-proxy
---
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-service-account
  namespace: flickr-api-proxy
  annotations:
    kubernetes.io/service-account.name: github-actions
type: kubernetes.io/service-account-token
